server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect